//! Proc macros for the MinnsDB WASM module SDK.
//!
//! These macros generate all the ABI glue so module authors never touch
//! `extern "C"`, `#[no_mangle]`, pointer arithmetic, or MessagePack directly.
//!
//! # Usage
//!
//! ```rust,ignore
//! use minns_sdk::prelude::*;
//!
//! #[minns_module(name = "my_agent", version = "0.1.0")]
//! mod my_agent {
//!     #[minns_function]
//!     fn greet(name: String) -> String {
//!         format!("Hello, {}!", name)
//!     }
//!
//!     #[minns_function]
//!     fn add(a: i64, b: i64) -> i64 {
//!         a + b
//!     }
//! }
//! ```

use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{parse_macro_input, ItemFn, ItemMod, LitStr};

/// Attribute macro applied to a `mod` block. Generates the WASM ABI exports:
/// `__minns_describe__`, `__minns_describe_len__`, `__minns_call__`, and `alloc`.
///
/// Functions inside the module annotated with `#[minns_function]` are
/// automatically registered and dispatched by `func_id`.
///
/// # Attributes
/// - `name = "module_name"` — module name reported to the runtime (required)
/// - `version = "0.1.0"` — module version (optional, defaults to "0.1.0")
#[proc_macro_attribute]
pub fn minns_module(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args = parse_macro_input!(attr as ModuleArgs);
    let input = parse_macro_input!(item as ItemMod);
    match generate_module(args, input) {
        Ok(tokens) => tokens.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

/// Marker attribute for functions inside a `#[minns_module]`. No code is
/// generated by this macro alone — the `#[minns_module]` macro scans for
/// items with this attribute and wires them into the dispatch table.
#[proc_macro_attribute]
pub fn minns_function(_attr: TokenStream, item: TokenStream) -> TokenStream {
    // Pass through unchanged — minns_module reads the attribute
    item
}

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

struct ModuleArgs {
    name: String,
    version: String,
}

impl syn::parse::Parse for ModuleArgs {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let mut name = None;
        let mut version = None;

        while !input.is_empty() {
            let ident: syn::Ident = input.parse()?;
            input.parse::<syn::Token![=]>()?;
            let value: LitStr = input.parse()?;

            match ident.to_string().as_str() {
                "name" => name = Some(value.value()),
                "version" => version = Some(value.value()),
                other => {
                    return Err(syn::Error::new(
                        ident.span(),
                        format!("unknown attribute: {}", other),
                    ))
                },
            }

            if input.peek(syn::Token![,]) {
                input.parse::<syn::Token![,]>()?;
            }
        }

        Ok(ModuleArgs {
            name: name.ok_or_else(|| input.error("missing `name` attribute"))?,
            version: version.unwrap_or_else(|| "0.1.0".into()),
        })
    }
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

fn generate_module(args: ModuleArgs, mut input: ItemMod) -> syn::Result<proc_macro2::TokenStream> {
    let mod_name = input.ident.clone();
    let module_name_str = &args.name;
    let module_version_str = &args.version;

    // Extract functions annotated with #[minns_function]
    let content = input.content.as_mut().ok_or_else(|| {
        syn::Error::new_spanned(&mod_name, "module must have a body (not just `mod name;`)")
    })?;

    let mut functions: Vec<FnEntry> = Vec::new();

    for item in &mut content.1 {
        if let syn::Item::Fn(func) = item {
            let has_attr = func
                .attrs
                .iter()
                .any(|a| a.path().is_ident("minns_function"));
            if has_attr {
                func.attrs.retain(|a| !a.path().is_ident("minns_function"));
                functions.push(extract_fn_entry(func)?);
            }
        }
    }

    // Generate the dispatch arms for __minns_call__
    let dispatch_arms: Vec<proc_macro2::TokenStream> = functions
        .iter()
        .enumerate()
        .map(|(id, entry)| {
            let fn_name = &entry.ident;
            let id_lit = id as i32;

            if entry.params.is_empty() {
                // No args — call directly
                quote! {
                    #id_lit => {
                        let result = #mod_name::#fn_name();
                        ::minns_sdk::abi::set_result(&result);
                        0
                    }
                }
            } else if entry.params.len() == 1 {
                // Single arg — deserialize directly
                let ty = &entry.params[0].1;
                quote! {
                    #id_lit => {
                        let arg: #ty = match ::minns_sdk::abi::read_args(__args_ptr, __args_len) {
                            Ok(v) => v,
                            Err(e) => {
                                ::minns_sdk::abi::set_result(&format!("arg decode error: {}", e));
                                return -1;
                            }
                        };
                        let result = #mod_name::#fn_name(arg);
                        ::minns_sdk::abi::set_result(&result);
                        0
                    }
                }
            } else {
                // Multiple args — deserialize as tuple
                let types: Vec<&syn::Type> = entry.params.iter().map(|(_, ty)| ty).collect();
                let names: Vec<syn::Ident> = entry
                    .params
                    .iter()
                    .enumerate()
                    .map(|(i, _)| format_ident!("__arg_{}", i))
                    .collect();
                let tuple_type = quote! { (#(#types),*) };
                let unpack = quote! { let (#(#names),*) = __args_tuple; };
                let call_args = quote! { #(#names),* };
                quote! {
                    #id_lit => {
                        let __args_tuple: #tuple_type = match ::minns_sdk::abi::read_args(__args_ptr, __args_len) {
                            Ok(v) => v,
                            Err(e) => {
                                ::minns_sdk::abi::set_result(&format!("arg decode error: {}", e));
                                return -1;
                            }
                        };
                        #unpack
                        let result = #mod_name::#fn_name(#call_args);
                        ::minns_sdk::abi::set_result(&result);
                        0
                    }
                }
            }
        })
        .collect();

    // Generate FunctionDef entries for the descriptor
    let fn_defs: Vec<proc_macro2::TokenStream> = functions
        .iter()
        .map(|entry| {
            let name_str = entry.ident.to_string();
            quote! {
                ::minns_sdk::types::FunctionDef {
                    name: #name_str.into(),
                    description: String::new(),
                }
            }
        })
        .collect();

    // Generate the full output
    let output = quote! {
        // The user's module with its functions
        #input

        // ── Generated ABI exports ──────────────────────────────────────

        #[no_mangle]
        pub extern "C" fn __minns_describe__() -> i32 {
            ::minns_sdk::abi::register_descriptor(&::minns_sdk::types::ModuleDescriptor {
                name: #module_name_str.into(),
                version: #module_version_str.into(),
                functions: vec![#(#fn_defs),*],
                triggers: vec![],
                permissions: vec![],
            })
        }

        #[no_mangle]
        pub extern "C" fn __minns_describe_len__() -> i32 {
            ::minns_sdk::abi::descriptor_len()
        }

        #[no_mangle]
        pub extern "C" fn __minns_call__(__func_id: i32, __args_ptr: i32, __args_len: i32) -> i32 {
            match __func_id {
                #(#dispatch_arms),*
                _ => {
                    ::minns_sdk::abi::set_result(&"unknown function ID");
                    -1
                }
            }
        }
    };

    Ok(output)
}

struct FnEntry {
    ident: syn::Ident,
    params: Vec<(syn::Ident, syn::Type)>,
}

fn extract_fn_entry(func: &ItemFn) -> syn::Result<FnEntry> {
    let ident = func.sig.ident.clone();
    let mut params = Vec::new();

    for arg in &func.sig.inputs {
        match arg {
            syn::FnArg::Typed(pat_type) => {
                let name = match pat_type.pat.as_ref() {
                    syn::Pat::Ident(pi) => pi.ident.clone(),
                    _ => {
                        return Err(syn::Error::new_spanned(
                            &pat_type.pat,
                            "expected simple parameter name",
                        ))
                    },
                };
                params.push((name, (*pat_type.ty).clone()));
            },
            syn::FnArg::Receiver(_) => {
                return Err(syn::Error::new_spanned(
                    arg,
                    "module functions cannot take self",
                ))
            },
        }
    }

    Ok(FnEntry { ident, params })
}
