// GraphEngine methods for ontology management: listing, upload, evolution, cascade inference.

use crate::llm_client::{LlmRequest, LlmResponse};
use crate::ontology_evolution::OntologyEvolutionEngine;

impl super::GraphEngine {
    /// List all registered ontology property IDs.
    pub fn list_ontology_property_ids(&self) -> Vec<String> {
        self.ontology.all_property_ids()
    }

    /// List all ontology properties as JSON-serializable values.
    pub fn list_ontology_properties_json(&self) -> Vec<serde_json::Value> {
        self.ontology
            .all_property_ids()
            .into_iter()
            .filter_map(|id| {
                let desc = self.ontology.resolve(&id)?;
                Some(serde_json::json!({
                    "id": desc.id,
                    "label": desc.label,
                    "comment": desc.comment,
                    "domain": desc.domain,
                    "range": desc.range,
                    "characteristics": desc.characteristics.iter().map(|c| format!("{:?}", c)).collect::<Vec<_>>(),
                    "sub_property_of": desc.sub_property_of,
                    "inverse_of": desc.inverse_of,
                    "append_only": desc.append_only,
                    "cascade_dependents": desc.cascade_dependents,
                    "cascade_dependent": desc.cascade_dependent,
                    "canonical_predicate": desc.canonical_predicate,
                }))
            })
            .collect()
    }

    /// Upload new ontology TTL content, register properties, and run LLM cascade inference.
    ///
    /// Returns `(properties_registered, cascade_updates)`.
    pub async fn upload_ontology_ttl(&self, ttl_content: &str) -> Result<(usize, usize), String> {
        // Phase 1: Parse TTL and register properties
        let before_ids: std::collections::HashSet<String> =
            self.ontology.all_property_ids().into_iter().collect();

        self.ontology
            .load_turtle_shared(ttl_content)
            .map_err(|e| format!("TTL parse error: {}", e))?;

        let after_ids: std::collections::HashSet<String> =
            self.ontology.all_property_ids().into_iter().collect();
        let new_count = after_ids.difference(&before_ids).count();

        tracing::info!(
            "Ontology upload: parsed TTL, {} new properties registered",
            new_count
        );

        // Phase 2: Run LLM cascade inference on the full registry
        let cascade_updates = self.run_ontology_cascade_inference().await.unwrap_or(0);

        // Phase 3: Write back updated TTL to disk for persistence
        if new_count > 0 {
            if let Err(e) = self.persist_ontology_cascade_updates() {
                tracing::warn!("Failed to persist cascade updates: {}", e);
            }
        }

        Ok((new_count, cascade_updates))
    }

    /// Run LLM cascade/temporal dependency inference across all ontology properties.
    ///
    /// Builds a prompt, sends it to the LLM, parses the response, and updates
    /// the OntologyRegistry with inferred cascade_dependents/cascade_dependent.
    pub async fn run_ontology_cascade_inference(&self) -> Result<usize, String> {
        let llm = match &self.unified_llm_client {
            Some(client) => client.clone(),
            None => {
                tracing::debug!("No LLM client available, skipping cascade inference");
                return Ok(0);
            },
        };

        let (system_prompt, user_prompt) =
            OntologyEvolutionEngine::build_cascade_inference_prompt(&self.ontology);

        tracing::info!(
            "Running LLM cascade inference on {} properties",
            self.ontology.all_property_ids().len()
        );

        let request = LlmRequest {
            system_prompt,
            user_prompt,
            temperature: 0.1,
            max_tokens: 2000,
            json_mode: true,
        };

        let response: LlmResponse = llm
            .complete(request)
            .await
            .map_err(|e| format!("LLM cascade inference failed: {}", e))?;

        let updated = OntologyEvolutionEngine::parse_cascade_inference_response(
            &response.content,
            &self.ontology,
        );

        tracing::info!("Cascade inference: updated {} properties", updated);

        // Persist to disk
        if updated > 0 {
            if let Err(e) = self.persist_ontology_cascade_updates() {
                tracing::warn!("Failed to persist cascade updates: {}", e);
            }
        }

        Ok(updated)
    }

    /// Write a `_cascade_inferred.ttl` file capturing current cascade relationships.
    ///
    /// This augments the hand-written TTL files so cascade info survives restart.
    fn persist_ontology_cascade_updates(&self) -> Result<(), String> {
        let mut ttl = String::new();
        ttl.push_str("## ── Auto-inferred cascade dependencies ──\n");
        ttl.push_str("## Generated by LLM cascade inference pass. Do not edit manually.\n\n");
        ttl.push_str("@prefix eg:   <http://minnsdb.local/ontology#> .\n");
        ttl.push_str("@prefix owl:  <http://www.w3.org/2002/07/owl#> .\n\n");

        let mut has_content = false;
        for pid in self.ontology.all_property_ids() {
            if let Some(desc) = self.ontology.resolve(&pid) {
                let has_deps = !desc.cascade_dependents.is_empty();
                let is_dep = desc.cascade_dependent;
                if has_deps || is_dep {
                    ttl.push_str(&format!("eg:{} a owl:ObjectProperty", pid));
                    if has_deps {
                        let deps: Vec<String> = desc
                            .cascade_dependents
                            .iter()
                            .map(|d| format!("eg:{}", d))
                            .collect();
                        ttl.push_str(&format!(" ;\n    eg:cascadeDependents {}", deps.join(", ")));
                    }
                    if is_dep {
                        ttl.push_str(" ;\n    eg:cascadeDependent \"true\"");
                    }
                    ttl.push_str(" .\n\n");
                    has_content = true;
                }
            }
        }

        if !has_content {
            return Ok(());
        }

        let path = std::path::PathBuf::from("data/ontology/_cascade_inferred.ttl");
        std::fs::write(&path, &ttl).map_err(|e| format!("Write failed: {}", e))?;
        tracing::info!("Persisted cascade dependencies to {:?}", path);
        Ok(())
    }

    /// Run behaviour inference: scan the graph for predicates not in the
    /// ontology, propose OWL characteristics (functional / symmetric /
    /// append-only / supersession-cascade) for those above `min_observations`.
    /// Returns the IDs of newly created proposals.
    ///
    /// Acquires the inference read lock for the snapshot scan, releases it,
    /// then takes the evolution write lock for proposal creation. No write
    /// lock is held across the LLM call (this method has no LLM call).
    pub async fn run_ontology_evolution_pass(&self) -> Result<Vec<u64>, String> {
        let stats = {
            let inference = self.inference.read().await;
            crate::ontology_evolution::OntologyEvolutionEngine::snapshot_predicate_stats(
                inference.graph(),
            )
        };
        let mut evolution = self.ontology_evolution.write().await;
        let behaviours = evolution.infer_behaviours(&stats, &self.ontology);
        if behaviours.is_empty() {
            return Ok(Vec::new());
        }
        Ok(evolution.create_proposals_from_inferred(&behaviours, &self.ontology, &stats))
    }

    /// LLM-assisted hierarchy discovery: scan the graph, build a prompt
    /// listing predicates not yet in the ontology, send to the LLM, then
    /// parse the response into proposals. Returns proposal IDs.
    ///
    /// No evolution lock is held across the LLM call. The graph snapshot
    /// is taken once at the start; the engine config (min_observations)
    /// is read under a brief lock.
    pub async fn run_ontology_hierarchy_discovery(&self) -> Result<Vec<u64>, String> {
        let llm = match &self.unified_llm_client {
            Some(client) => client.clone(),
            None => {
                tracing::debug!("No LLM client available, skipping hierarchy discovery");
                return Ok(Vec::new());
            },
        };

        // Snapshot stats once. Released before LLM call.
        let stats = {
            let inference = self.inference.read().await;
            crate::ontology_evolution::OntologyEvolutionEngine::snapshot_predicate_stats(
                inference.graph(),
            )
        };
        let min_obs = self.ontology_evolution.read().await.min_observations();
        let prompt =
            crate::ontology_evolution::OntologyEvolutionEngine::build_hierarchy_discovery_prompt(
                &stats,
                &self.ontology,
                min_obs,
            );
        let (system_prompt, user_prompt) = match prompt {
            Some(p) => p,
            None => return Ok(Vec::new()),
        };

        let request = crate::llm_client::LlmRequest {
            system_prompt,
            user_prompt,
            temperature: 0.1,
            max_tokens: 2000,
            json_mode: true,
        };
        let response = llm
            .complete(request)
            .await
            .map_err(|e| format!("Hierarchy discovery LLM call failed: {}", e))?;

        // Parse + create proposals under the engine write lock.
        let mut evolution = self.ontology_evolution.write().await;
        Ok(evolution.parse_hierarchy_response(&response.content, &self.ontology, &stats))
    }

    /// List per-predicate stats derived from a fresh graph scan, plus
    /// proposal-side aggregate counts. The endpoint keeps its historical
    /// `/api/ontology/observations` name — under the new design these are
    /// graph-derived predicate stats rather than per-edge observations.
    pub async fn list_ontology_observations(&self) -> (Vec<serde_json::Value>, serde_json::Value) {
        let stats = {
            let inference = self.inference.read().await;
            crate::ontology_evolution::OntologyEvolutionEngine::snapshot_predicate_stats(
                inference.graph(),
            )
        };
        let observations: Vec<serde_json::Value> = stats
            .iter()
            .map(|s| {
                serde_json::json!({
                    "category": s.category,
                    "predicate": s.predicate,
                    "edge_count": s.edge_count,
                    "forward_active": s.forward_active,
                    "reverse_active": s.reverse_active,
                    "superseded": s.superseded,
                    "distinct_subjects": s.distinct_subjects,
                    "single_value_subjects": s.single_value_subjects,
                    "domain_types": s.domain_types,
                    "range_types": s.range_types,
                    "first_valid_from": s.first_valid_from,
                    "last_valid_from": s.last_valid_from,
                })
            })
            .collect();
        let total_edges: u64 = stats.iter().map(|s| s.edge_count).sum();
        let evolution = self.ontology_evolution.read().await;
        let proposal_stats = evolution.stats();
        let stats_json = serde_json::json!({
            "tracked_predicates": stats.len(),
            "total_edge_count": total_edges,
            "pending_proposals": proposal_stats.pending_proposals,
            "approved_proposals": proposal_stats.approved_proposals,
            "rejected_proposals": proposal_stats.rejected_proposals,
            "applied_proposals": proposal_stats.applied_proposals,
        });
        (observations, stats_json)
    }

    /// List all evolution proposals (any status).
    pub async fn ontology_evolution_proposals(
        &self,
    ) -> Vec<crate::ontology_evolution::OntologyProposal> {
        let evolution = self.ontology_evolution.read().await;
        evolution.proposals().to_vec()
    }

    /// Approve and apply a proposal. Returns the number of ontology
    /// properties registered.
    ///
    /// Idempotent on retry: a proposal that was already approved but whose
    /// previous apply failed (e.g. disk write error) can be re-driven by
    /// calling this again. Pending → Approved → Applied is the happy path;
    /// Approved → Applied is the retry path.
    pub async fn approve_and_apply_ontology_proposal(&self, id: u64) -> Result<usize, String> {
        let mut evolution = self.ontology_evolution.write().await;
        let current = evolution
            .get_proposal(id)
            .map(|p| p.status.clone())
            .ok_or_else(|| format!("Proposal {} not found", id))?;
        match current {
            crate::ontology_evolution::ProposalStatus::Pending => {
                // Transition Pending → Approved before apply.
                evolution.approve_proposal(id);
            },
            crate::ontology_evolution::ProposalStatus::Approved => {
                // Retry path: previous apply failed but proposal is already
                // approved. Skip the transition and proceed to apply.
            },
            other => {
                return Err(format!("Proposal {} is {:?}, cannot apply", id, other));
            },
        }
        evolution
            .apply_proposal(id, &self.ontology)
            .map_err(|e| e.to_string())
    }

    /// Reject a proposal. Returns true if the proposal was found and
    /// transitioned to Rejected.
    pub async fn reject_ontology_proposal(&self, id: u64) -> bool {
        let mut evolution = self.ontology_evolution.write().await;
        evolution.reject_proposal(id)
    }

    /// Evolution-side proposal counts. For predicate-stat counts (which
    /// come from a fresh graph scan), see `list_ontology_observations`.
    pub async fn ontology_evolution_stats(&self) -> serde_json::Value {
        let evolution = self.ontology_evolution.read().await;
        let s = evolution.stats();
        serde_json::json!({
            "pending_proposals": s.pending_proposals,
            "approved_proposals": s.approved_proposals,
            "rejected_proposals": s.rejected_proposals,
            "applied_proposals": s.applied_proposals,
        })
    }
}
